extends Control

@onready var hit_points_label = $HitPoints
@onready var bullets_label = $Bullets
@onready var stars_label = $StarsLeft
@onready var you_won_label = $YouWonLabel
@onready var game_over_label = $GameOverLabel


func update_values(hp: int, bullets: int) -> void:
	hit_points_label.text = "HP: %d" % hp
	bullets_label.text = "Bullets: %d" % bullets

func update_stars_left(count: int) -> void:
	stars_label.text = "Stars: %d" % count

func show_you_won():
	you_won_label.visible = true

func show_game_over():
	game_over_label.visible = true
